version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-app
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - laravel
        ports:
            - "9000:9000"
        depends_on:
            - mysql

    mysql:
        image: mysql:5.7
        container_name: laravel-mysql
        restart: unless-stopped
        tty: true
        environment:
            MYSQL_DATABASE: medical_records
            MYSQL_USER: medical_user
            MYSQL_PASSWORD: medicalpass
            MYSQL_ROOT_PASSWORD: medicalpass
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - laravel
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 30s
            timeout: 10s
            retries: 5

networks:
    laravel:
        driver: bridge

volumes:
    dbdata:
        driver: local
