version: '3.8'

services:
    # MySQL Service
    mysql:
        image: mysql:5.7
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: laravel_db
            MYSQL_USER: laravel_db
            MYSQL_PASSWORD: secret123
            MYSQL_ROOT_PASSWORD: secret123
        volumes:
            - mysql-data:/var/lib/mysql

    # PHP Service
    php:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www
        depends_on:
            - mysql

    # Nginx Service
    nginx:
        image: nginx:alpine
        ports:
            - "80:80"
        volumes:
            - .:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php

volumes:
    mysql-data:
